#!/bin/bash
### BEGIN INIT INFO
# Provides:          mshattori
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: thingworx demo
### END INIT INFO

start() {
    echo -n "Starting thingworx demo client: "	
    /home/pi/thingworx_demo/main.py
    echo "done"
    return 0
}

stop() {
    kill $(cat /tmp/thingworx.pid)
    rm -f /tmp/thingworx.pid
    return 0
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
esac
